name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov

    - name: Show current directory
      run: pwd

    - name: List root files and folders
      run: ls -la

    - name: List tests folder
      run: ls -la tests || echo "No tests folder found"

    - name: List life_expectancy folder
      run: ls -la life_expectancy || echo "No life_expectancy folder found"

    - name: Run tests with coverage
      run: pytest --cov=life_expectancy tests
