name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Check Python version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install pandas toml pytest pytest-cov

    - name: Check pytest installation
      run: pytest --version

    - name: List root folder contents
      run: ls -la

    - name: List life_expectancy folder contents
      run: ls -la life_expectancy

    - name: Run tests with coverage
      run: pytest --cov=life_expectancy --cov-fail-under=0 life_expectancy/tests